FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates && rm -rf /var/lib/apt/lists/*

ARG TARGETARCH
COPY binaries/linux/${TARGETARCH}/sieve /usr/local/bin/sieve

WORKDIR /app

ENTRYPOINT ["sieve"]
